# Generated by Django 3.2.6 on 2021-11-22 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0009_review_product_created_at'),
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_list', models.ManyToManyField(blank=True, null=True, related_name='wishlist_of_products', to='product.ProductVersion')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_of_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_of_basket', to='checkout.basket')),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.billingaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_of_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.basket')),
                ('product_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productversion')),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='product_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='basket_of_products', to='checkout.BasketItem'),
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basket_of_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
