# Generated by Django 3.2.6 on 2021-11-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='is_order_placed',
            field=models.BooleanField(default=False),
        ),
    ]
