# Generated by Django 3.2.6 on 2021-11-24 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_basket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_of_basket', to='checkout.basket'),
        ),
    ]
