# Generated by Django 3.2.6 on 2021-10-17 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=255)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Review_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=50)),
                ('reviewer_email', models.EmailField(max_length=254)),
                ('review_text', models.TextField()),
                ('review_star', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_of_product', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('Dodger Blue 3', 'Dodger Blue 3'), ('Hex Cyan', 'Hex Cyan'), ('Tomato', 'Tomato'), ('Pumpkin', 'Pumpkin'), ('Dark Salmon', 'Dark Salmon'), ('Deep Blue Sky', 'Deep Blue Sky'), ('Light Salmon', 'Light Salmon')], max_length=255)),
                ('stock_quantity', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('is_main', models.BooleanField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version', to='product.product')),
            ],
        ),
    ]
