# Generated by Django 3.2.6 on 2021-11-11 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211017_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='color',
            field=models.CharField(choices=[('dodgerblue3', 'dodgerblue3'), ('hexcyan', 'hexcyan'), ('tomato', 'tomato'), ('pumpkin', 'pumpkin'), ('darksalmon', 'darksalmon'), ('deepbluesky', 'deepbluesky'), ('lightsalmon', 'lightsalmon')], max_length=255),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='size',
            field=models.CharField(choices=[('xs', 'xs'), ('s', 's'), ('m', 'm'), ('l', 'l'), ('xl', 'xl')], max_length=255),
        ),
    ]
