# Generated by Django 3.2.6 on 2021-11-18 14:29

from django.db import migrations
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_review_product_review_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_product',
            name='review_star',
            field=product.models.IntegerRangeField(blank=True, null=True),
        ),
    ]
