# Generated by Django 3.2.6 on 2021-11-18 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_review_product_review_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
