# Generated by Django 3.2.6 on 2021-11-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_review_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productversion',
            name='photo',
        ),
    ]
