# Generated by Django 3.2.6 on 2021-11-21 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_review_product_created_at'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('is_main', models.BooleanField(default=False)),
                ('product_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_of_pv', to='product.productversion')),
            ],
        ),
    ]
